ALTER TABLE floor_elements
    ADD COLUMN IF NOT EXISTS x2       INT,
    ADD COLUMN IF NOT EXISTS y2       INT,
    ADD COLUMN IF NOT EXISTS width    INT NOT NULL DEFAULT 60,
    ADD COLUMN IF NOT EXISTS rotation INT NOT NULL DEFAULT 0;
